"""init_db

Revision ID: 192123bb916f
Revises: 
Create Date: 2024-07-05 00:01:26.926337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192123bb916f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id', 'id')
    )
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=False)
    op.create_index(op.f('ix_categorias_pk_id'), 'categorias', ['pk_id'], unique=False)
    op.create_table('centro_treinamento',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id', 'id')
    )
    op.create_index(op.f('ix_centro_treinamento_nome'), 'centro_treinamento', ['nome'], unique=False)
    op.create_index(op.f('ix_centro_treinamento_pk_id'), 'centro_treinamento', ['pk_id'], unique=False)
    op.create_table('atletas',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('centro_treinamento_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.pk_id'], ),
    sa.ForeignKeyConstraint(['centro_treinamento_id'], ['centro_treinamento.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id', 'id')
    )
    op.create_index(op.f('ix_atletas_nome'), 'atletas', ['nome'], unique=False)
    op.create_index(op.f('ix_atletas_pk_id'), 'atletas', ['pk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atletas_pk_id'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_nome'), table_name='atletas')
    op.drop_table('atletas')
    op.drop_index(op.f('ix_centro_treinamento_pk_id'), table_name='centro_treinamento')
    op.drop_index(op.f('ix_centro_treinamento_nome'), table_name='centro_treinamento')
    op.drop_table('centro_treinamento')
    op.drop_index(op.f('ix_categorias_pk_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
